### ISSUE TITLE
Use mount and end_play 

### ISSUE THREAD

**Issue by ioggstream** [ioggstream/python-course#19]
This play uses the mount module in check mode. If the device is already mounted, don't do the play.

``` 
 - name: Get the host mongo VG path.
    set_fact:
      mongo_dev: >-
        /dev/mapper/vg_mongo_{{ansible_hostname[-2:]}}-lv_mongodata

  - name: Check if mongod is on storage
    register: mongod_on_storage
    check_mode: yes
    mount:
      path: /var/lib/mongo
      src: "{{mongo_dev}}"
      fstype: xfs
      state: mounted

# put in 03_facts_and_variables.ipynb with assert and fail
  - name: Stop if mongo_dev already mounted on /var/lib/mongo  
    meta: end_play
    when: mongod_on_storage.changed == false
```
