### ISSUE TITLE
add lookup 

### ISSUE THREAD

**Issue by ioggstream** [ioggstream/python-course#26]
```
- name: Set authorized key took from file
  authorized_key:
    user: charlie
    state: present
    key: "{{ lookup('file', '/home/charlie/.ssh/id_rsa.pub') }}"
```
