### ISSUE TITLE
mysql-101: create docker-compose for course environment

### ISSUE THREAD

**Issue by ioggstream** [ioggstream/python-course#35]
example file

```
version: '3'

services:
  mysql:
    image: centos:7
    command: tail -f /etc/hosts
    networks:
    - be

networks:
  be:
```
