### ISSUE TITLE
ansible-101: apt should not use with_items

### ISSUE THREAD

**Issue by ioggstream** [ioggstream/python-course#46]
## I expect

`apt` to use this syntax

```

- name: Install a list of packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - foo
    - foo-tools

```

## instead

it uses 

```
      apt: name={{item}} state=present
      with_items:
        - python
        - python-dev
```

## Files

```
# check with 
find . -name \*.yml -exec grep -C4 -nH apt {} \;

```

**Comment by nuvoletta8** [comment]
```
# Run this with
#
#   #ansible-playbook -i inventory site.yml
#
- hosts: course
  tasks:

    - name: Create a file from a template
      template: src=mytemplate.j2 dest=/tmp/template.conf

    - name: Ensure needed packages are present and eventually install them
      apt: name="{{packages}}"
      vars:
        packages: 
          - python
          - python-dev
      ignore_errors: yes  #  ignore errors during the course (eg. connectivity)
```
