### ISSUE TITLE
mysql 101: add selinux policy for relocating datadir

### ISSUE THREAD

**Issue by ioggstream** [ioggstream/python-course#5]
When using selinux, before relocating datadir you need to:

  - modify the selinux policy
  - apply the new policy to the new datadit

```

 [root@boxy ~]# semanage port -a -t mysqld_port_t -p tcp 3307 
You'll need to install the policycoreutils-python package to use the semanage utility.
The semanage utility changes various SELinux settings.  In this case, it adds (-a) a type (-t  mysqld_port_t) to the port mappings for port 3307 using TCP as its protocol (-p tcp). When MySQL (through the mysqld_safe process) tries to access that port, SELinux recognises that the port has a type that is approved for such access by the policy.

We can also allow MySQL to use the /datadir directory: 

```
semanage port -a -t mysqld_port_t -p tcp 3307 
semanage fcontext -a -t mysqld_db_t "/datadir(/.*)?"
restorecon -Rv /datadir
```

**Comment by ioggstream** [comment]
Anche apparmor
```
  - name: Apparmor - Update profile on new datadir.
    lineinfile:
      dest: '/etc/apparmor.d/local/usr.sbin.mysqld'
      state: present
      line: "{{item.path}} {{item.acl}},"
    with_items:
     - { path: '/diskb/data1/',   acl: 'r'}
     - { path: '/diskb/data1/**', acl: 'rwk'}
     - { path: '/diskb/log/',   acl: 'r'}
     - { path: '/diskb/log/**', acl: 'rwk'}
     - { path: '/diskb/binlog/',   acl: 'r'}
     - { path: '/diskb/binlog/**', acl: 'rwk'}
     - { path: '/diskb/backup/',   acl: 'r'}
     - { path: '/diskb/backup/**', acl: 'rwk'}

  - name: Apparmor - reload profile
    service: name=apparmor state=restarted
```
